using UnityEngine;
using System.Collections;
using System.Collections.Generic;
using KillingMahjong.EngineData;
using KillingMahjong.Managers;
using KillingMahjong.Common;

namespace KillingMahjong.UI
{
    [RequireComponent(typeof(GameUIManager))]
    public partial class GameUIVisualController : MonoBehaviour
    {
        // partial の責務:
        // - GameUIVisualController.Rebuild.cs: 盤面全体の再描画
        // - GameUIVisualController.StateSync.cs: 透視・フリテンなど状態表示の同期
        // - GameUIVisualController.Tiles.cs: 個々の牌UIの初期化と差分更新

        private GameUIManager uiManager;
        private List<int> _lastSuppressedIndices = new List<int>();
        
        [Header("Animation Settings")]
        [Tooltip("アニメーション専用のキャンバス。未設定の場合は自動生成されます。")]
        [SerializeField] private Canvas _animCanvas;
        private bool _isAnimCanvasAutoGenerated = false;
        
        // 進行中のアニメーションのクリーンアップ処理を保持するリスト（Rebuild時に即時完了させるため）
        private List<System.Action> _activeAnimationCleanups = new List<System.Action>();
        [Header("Pool Settings")]
        public TilePoolManager poolManager;

        /// <summary>牌の移動・ソートアニメーション（分離クラス）</summary>
        private TileMoveAnimator _moveAnimator;
        /// <summary>透視スキルの公開牌演出（分離クラス）</summary>
        private ExposedTileEffectPlayer _exposedEffectPlayer;

        public void Setup(GameUIManager manager)
        {
            this.uiManager = manager;
            _moveAnimator = new TileMoveAnimator(manager, this);
            _exposedEffectPlayer = new ExposedTileEffectPlayer(manager, this);
            
            if (poolManager != null)
            {
                poolManager.InitializePool(manager);
            }
            else
            {
                Debug.LogError("[GameUIVisualController] TilePoolManager is not assigned!");
            }

            // アニメーション専用のキャンバスを初期化
            if (_animCanvas == null)
            {
                _isAnimCanvasAutoGenerated = true;
                GameObject animObj = new GameObject("AnimationCanvas");
                animObj.transform.SetParent(this.transform, false);
                
                // 親のキャンバススケールを引き継ぐため、RectTransform を全体にストレッチ
                RectTransform rt = animObj.AddComponent<RectTransform>();
                rt.anchorMin = Vector2.zero;
                rt.anchorMax = Vector2.one;
                rt.sizeDelta = Vector2.zero;
                rt.anchoredPosition = Vector2.zero;

                _animCanvas = animObj.AddComponent<Canvas>();
                // renderModeは設定せず親に依存。最前面にだけ出す。
                _animCanvas.overrideSorting = true;
                _animCanvas.sortingOrder = UISortingOrders.TileAnimationLayer;
                
                var cg = animObj.AddComponent<CanvasGroup>();
                cg.blocksRaycasts = false;
                cg.interactable = false;
            }

            var board = BoardStateManager.Instance;
            board.OnBoardStateRebuilt += RebuildAllTilesFromState;
            board.OnSelectionChanged += UpdateSelectedTileVisuals;
            board.OnTileMovedToHand += HandleTileMovedToHand;
            board.OnTileMovedToWall += HandleTileMovedToWall;
        }



        public void ReturnTileToPool(GameObject obj)
        {
            if (poolManager != null) poolManager.ReturnTileToPool(obj);
        }

        private void OnDestroy()
        {
            if (BoardStateManager.Instance != null)
            {
                var board = BoardStateManager.Instance;
                board.OnBoardStateRebuilt -= RebuildAllTilesFromState;
                board.OnSelectionChanged -= UpdateSelectedTileVisuals;
                board.OnTileMovedToHand -= HandleTileMovedToHand;
                board.OnTileMovedToWall -= HandleTileMovedToWall;
            }
        }

        public void RebuildAllTilesFromState()
        {
            RebuildAllTilesFromState(null);
        }

        private List<int> _lastWallIds = new List<int>();
        private List<int> _lastHandIds = new List<int>();

        /// <summary>
        /// 差分リビルドのキャッシュを捨てて、次回を必ずフルリビルドにする。
        ///
        /// RebuildAllTilesFromState は「前回と牌IDの構成が同じなら UI はそのままでよい」と
        /// 判断して再生成を省く。だが盤面の牌をプールへ返却したあとは UI 側に牌が残っておらず、
        /// この判断が成立しない。返却したら必ず呼んでキャッシュを無効化すること。
        /// </summary>
        public void InvalidateRebuildCache()
        {
            _lastWallIds.Clear();
            _lastHandIds.Clear();
        }

        public IEnumerator PlayHandSortAnimationRoutine()
        {
            return _moveAnimator.PlayHandSortAnimationRoutine();
        }


        public IEnumerator PlayTransitionAnimationRoutine(System.Action onUpdateState)
        {
            return _moveAnimator.PlayTransitionAnimationRoutine(onUpdateState);
        }

        /// <summary>Rebuildの差分検出用キャッシュを現在の盤面状態と同期する（TileMoveAnimatorから使用）</summary>
        internal void SyncRebuildCache()
        {
            _lastWallIds = new List<int>(BoardStateManager.Instance.CurrentWallTiles);
            _lastHandIds = new List<int>(BoardStateManager.Instance.CurrentHandTiles);
        }
    }
}
