using UnityEngine;
using System.Collections;
using System.Collections.Generic;
using KillingMahjong.EngineData;
using KillingMahjong.Managers;

namespace KillingMahjong.UI
{
    [RequireComponent(typeof(GameUIManager))]
    public class GameUIVisualController : MonoBehaviour
    {
        private GameUIManager uiManager;
        private List<int> _lastSuppressedIndices = new List<int>();
        
        [Header("Animation Settings")]
        [Tooltip("アニメーション専用のキャンバス。未設定の場合は自動生成されます。")]
        [SerializeField] private Canvas _animCanvas;
        private bool _isAnimCanvasAutoGenerated = false;
        
        // 進行中のアニメーションのクリーンアップ処理を保持するリスト（Rebuild時に即時完了させるため）
        private List<System.Action> _activeAnimationCleanups = new List<System.Action>();
        [Header("Pool Settings")]
        public TilePoolManager poolManager;

        public void Setup(GameUIManager manager)
        {
            this.uiManager = manager;
            
            if (poolManager != null)
            {
                poolManager.InitializePool(manager);
            }
            else
            {
                Debug.LogError("[GameUIVisualController] TilePoolManager is not assigned!");
            }

            // アニメーション専用のキャンバスを初期化
            if (_animCanvas == null)
            {
                _isAnimCanvasAutoGenerated = true;
                GameObject animObj = new GameObject("AnimationCanvas");
                animObj.transform.SetParent(this.transform, false);
                
                // 親のキャンバススケールを引き継ぐため、RectTransform を全体にストレッチ
                RectTransform rt = animObj.AddComponent<RectTransform>();
                rt.anchorMin = Vector2.zero;
                rt.anchorMax = Vector2.one;
                rt.sizeDelta = Vector2.zero;
                rt.anchoredPosition = Vector2.zero;

                _animCanvas = animObj.AddComponent<Canvas>();
                // renderModeは設定せず親に依存。最前面にだけ出す。
                _animCanvas.overrideSorting = true;
                _animCanvas.sortingOrder = 999;
                
                var cg = animObj.AddComponent<CanvasGroup>();
                cg.blocksRaycasts = false;
                cg.interactable = false;
            }

            var board = BoardStateManager.Instance;
            board.OnBoardStateRebuilt += RebuildAllTilesFromState;
            board.OnSelectionChanged += UpdateSelectedTileVisuals;
            board.OnTileMovedToHand += HandleTileMovedToHand;
            board.OnTileMovedToWall += HandleTileMovedToWall;
        }



        public void ReturnTileToPool(GameObject obj)
        {
            if (poolManager != null) poolManager.ReturnTileToPool(obj);
        }

        private void OnDestroy()
        {
            if (BoardStateManager.Instance != null)
            {
                var board = BoardStateManager.Instance;
                board.OnBoardStateRebuilt -= RebuildAllTilesFromState;
                board.OnSelectionChanged -= UpdateSelectedTileVisuals;
                board.OnTileMovedToHand -= HandleTileMovedToHand;
                board.OnTileMovedToWall -= HandleTileMovedToWall;
            }
        }

        public void RebuildAllTilesFromState()
        {
            RebuildAllTilesFromState(null);
        }

        private List<int> _lastWallIds = new List<int>();
        private List<int> _lastHandIds = new List<int>();

        public void RebuildAllTilesFromState(List<int> suppressRevealWallIndexes)
        {
            // --- アニメーション競合防止 ---
            foreach (var cleanup in _activeAnimationCleanups)
            {
                cleanup?.Invoke();
            }
            _activeAnimationCleanups.Clear();

            if (uiManager.IsTransitioning)
            {
                Debug.Log("[GameUIVisualController] IsTransitioning is true. Skipping RebuildAllTilesFromState to prevent visible tile movement.");
                return;
            }

            var board = BoardStateManager.Instance;
            List<int> currentWallIds = new List<int>(board.CurrentWallTiles);
            List<int> currentHandIds = new List<int>(board.CurrentHandTiles);

            bool needFullRebuild = true;

            if (_lastWallIds.Count == currentWallIds.Count && _lastHandIds.Count == currentHandIds.Count)
            {
                List<int> oldWallIds = new List<int>(_lastWallIds);
                List<int> newWallIds = new List<int>(currentWallIds);
                foreach (int id in _lastWallIds)
                {
                    if (newWallIds.Contains(id)) { newWallIds.Remove(id); oldWallIds.Remove(id); }
                }

                List<int> oldHandIds = new List<int>(_lastHandIds);
                List<int> newHandIds = new List<int>(currentHandIds);
                foreach (int id in _lastHandIds)
                {
                    if (newHandIds.Contains(id)) { newHandIds.Remove(id); oldHandIds.Remove(id); }
                }

                if (oldWallIds.Count == newWallIds.Count && oldHandIds.Count == newHandIds.Count)
                {
                    bool success = true;
                    for (int i = 0; i < oldWallIds.Count; i++) success &= UpdateTileIdInUI(oldWallIds[i], newWallIds[i]);
                    for (int i = 0; i < oldHandIds.Count; i++) success &= UpdateTileIdInUI(oldHandIds[i], newHandIds[i]);

                    if (success)
                    {
                        needFullRebuild = false;
                    }
                }
            }

            _lastWallIds = currentWallIds;
            _lastHandIds = currentHandIds;

            _lastSuppressedIndices.Clear();
            if (uiManager.TilePrefab == null) return;
            
            bool isGameEndPhase = uiManager.CurrentPhaseStatus == RoundStatus.Agari || 
                                  uiManager.CurrentPhaseStatus == RoundStatus.Ron || 
                                  uiManager.CurrentPhaseStatus == RoundStatus.Result || 
                                  uiManager.CurrentPhaseStatus == RoundStatus.Draw;
            if (isGameEndPhase) return;

            if (needFullRebuild)
            {
                // 1. HandUI / WallUI を一括クリア
                if (uiManager.HandUI != null)
                {
                    for (int i = uiManager.HandUI.GetHandSlots().Count - 1; i >= 0; i--)
                    {
                        Transform t = uiManager.HandUI.GetHandSlots()[i];
                        if (t != null) {
                            poolManager.ReturnTileToPool(t.gameObject);
                        }
                    }
                    uiManager.HandUI.GetHandSlots().Clear();
                }
                if (uiManager.WallUI != null)
                {
                    // 矢印インジケータを牌スロットから安全に切り離してからプールに返す
                    uiManager.WallUI.SetActiveDiscardTile(null);
                    for (int i = uiManager.WallUI.GetWallSlots().Count - 1; i >= 0; i--)
                    {
                        Transform t = uiManager.WallUI.GetWallSlots()[i];
                        if (t != null) {
                            poolManager.ReturnTileToPool(t.gameObject);
                        }
                    }
                    uiManager.WallUI.GetWallSlots().Clear();
                }

                if (uiManager.WallUI != null)
                {
                    List<int> combinedIds = new List<int>(board.CurrentWallTiles);
                    combinedIds.AddRange(board.CurrentHandTiles);

                    List<RectTransform> combinedGenerated = new List<RectTransform>();
                    foreach (var id in combinedIds)
                    {
                        GameObject obj = poolManager.GetTileById(id, transform, uiManager);
                        RectTransform rt = obj.GetComponent<RectTransform>() ?? obj.transform as RectTransform;
                        if (rt != null)
                        {
                            InitializeTileComponent(rt, id, false);
                            combinedGenerated.Add(rt);
                        }
                    }

                    uiManager.WallUI.LayoutWallTiles(combinedGenerated, combinedIds, board.CurrentWaitTiles, uiManager.CurrentPhaseStatus == RoundStatus.Discard);

                    if (uiManager.HandUI != null)
                    {
                        List<int> localExposedActualIds = new List<int>();
                        foreach (int exposedIdx in board.ExposedLocalHandWallIndexes)
                        {
                            if (exposedIdx >= 0 && exposedIdx < board.OriginalWallTiles.Count)
                            {
                                localExposedActualIds.Add(board.OriginalWallTiles[exposedIdx]);
                            }
                        }

                        foreach (var id in board.CurrentHandTiles)
                        {
                            RectTransform rt = uiManager.WallUI.GrabTileById(id);
                            if (rt != null)
                            {
                                InitializeTileComponent(rt, id, true);
                                uiManager.HandUI.AddTileToHand(rt, id);
                            }
                            else
                            {
                                Debug.LogWarning($"[Visual] Failed to grab tile by id: {id} for Local Hand!");
                            }
                        }
                        
                        UnityEngine.UI.LayoutRebuilder.ForceRebuildLayoutImmediate(uiManager.HandUI.GetComponent<RectTransform>());
                        UnityEngine.UI.LayoutRebuilder.ForceRebuildLayoutImmediate(uiManager.WallUI.GetComponent<RectTransform>());
                    }
                }

                // 3. Enemy HandUI (フルリビルド)
                if (uiManager.EnemyHandUI != null)
                {
                    for (int i = uiManager.EnemyHandUI.GetHandSlots().Count - 1; i >= 0; i--)
                    {
                        Transform t = uiManager.EnemyHandUI.GetHandSlots()[i];
                        if (t != null) poolManager.ReturnTileToPool(t.gameObject);
                    }
                    uiManager.EnemyHandUI.GetHandSlots().Clear();
                    uiManager.EnemyHandUI.ClearHand();

                    List<int> exposedEncodedIds = new List<int>();
                    foreach (int exposedIdx in board.ExposedEnemyHandWallIndexes)
                    {
                        if (exposedIdx >= 0 && exposedIdx < board.OriginalEnemyWallTiles.Count)
                        {
                            exposedEncodedIds.Add(board.OriginalEnemyWallTiles[exposedIdx]);
                        }
                    }

                    if (board.CurrentEnemyHandTiles != null && board.CurrentEnemyHandTiles.Count > 0)
                    {
                        uiManager.EnemyHandUI.gameObject.SetActive(true);

                        for (int i = 0; i < board.CurrentEnemyHandTiles.Count; i++)
                        {
                            int currentTileVal = board.CurrentEnemyHandTiles[i];
                            GameObject obj = poolManager.GetTileById(currentTileVal, transform, uiManager);
                            RectTransform rt = obj.GetComponent<RectTransform>() ?? obj.transform as RectTransform;
                            if (rt != null) {
                                int visualId = -1;
                                int actualTileId = currentTileVal;

                                InitializeTileComponent(rt, visualId, false);
                                uiManager.EnemyHandUI.AddEnemyTile(rt, visualId, actualTileId);

                                if (exposedEncodedIds.Contains(actualTileId))
                                {
                                    exposedEncodedIds.Remove(actualTileId);
                                    uiManager.EnemyHandUI.RevealTileByIndex(i);
                                }
                            }
                        }
                    }
                }

                // 4. Enemy WallUI (フルリビルド)
                if (uiManager.EnemyWallUI != null)
                {
                    for (int i = uiManager.EnemyWallUI.GetEnemyWallSlots().Count - 1; i >= 0; i--)
                    {
                        Transform t = uiManager.EnemyWallUI.GetEnemyWallSlots()[i];
                        if (t != null) poolManager.ReturnTileToPool(t.gameObject);
                    }
                    uiManager.EnemyWallUI.GetEnemyWallSlots().Clear();

                    if (uiManager.CurrentPhaseStatus == RoundStatus.Discard && suppressRevealWallIndexes == null)
                    {
                        uiManager.EnemyWallUI.gameObject.SetActive(false);
                    }
                    else
                    {
                        uiManager.EnemyWallUI.gameObject.SetActive(true);
                        List<RectTransform> enemyWallGenerated = new List<RectTransform>();
                        List<int> displayIdsForWall = new List<int>();

                        List<int> handTilesToRemove = new List<int>();
                        if (board.CurrentEnemyHandTiles != null && uiManager.CurrentPhaseStatus >= RoundStatus.Discard)
                        {
                            handTilesToRemove.AddRange(board.CurrentEnemyHandTiles);
                        }

                        for (int i = 0; i < board.OriginalEnemyWallTiles.Count; i++)
                        {
                            int actualTileId = board.OriginalEnemyWallTiles[i];

                            if (handTilesToRemove.Contains(actualTileId))
                            {
                                handTilesToRemove.Remove(actualTileId);
                                continue;
                            }

                            displayIdsForWall.Add(actualTileId);

                            GameObject obj = poolManager.GetTileById(actualTileId, transform, uiManager);
                            RectTransform rt = obj.GetComponent<RectTransform>() ?? obj.transform as RectTransform;
                            if (rt != null) {
                                int visualId = -1;
                                bool isExposedInWall = board.ExposedEnemyHandWallIndexes.Contains(i);
                                if (isExposedInWall) visualId = actualTileId;
                                
                                InitializeTileComponent(rt, visualId, false);
                                
                                var interactions = rt.GetComponentsInChildren<TileInteraction>(true);
                                foreach(var interaction in interactions) interaction.enabled = false;
                                var visual = rt.GetComponent<TileVisual>();
                                if (visual != null) visual.SetHoverHighlight(false);
                                var images = rt.GetComponentsInChildren<UnityEngine.UI.Image>(true);
                                foreach(var img in images) img.raycastTarget = false;
                                
                                var btn = rt.gameObject.GetComponent<UnityEngine.UI.Button>();
                                if (btn != null) btn.interactable = false;

                                enemyWallGenerated.Add(rt);
                            }
                        }
                        uiManager.EnemyWallUI.LayoutEnemyWallTiles(enemyWallGenerated, displayIdsForWall, uiManager.CurrentPhaseStatus == RoundStatus.Discard);
                    }
                }
            } // End of needFullRebuild
            else
            {
                // 差分同期 (Enemy ツモ処理など)
                if (uiManager.EnemyHandUI != null && uiManager.EnemyWallUI != null)
                {
                    int currentHandCount = uiManager.EnemyHandUI.GetHandSlots().Count;
                    int targetHandCount = board.CurrentEnemyHandTiles != null ? board.CurrentEnemyHandTiles.Count : 0;
                    
                    if (currentHandCount < targetHandCount)
                    {
                        // ツモ（EnemyWall -> EnemyHand）
                        int drawCount = targetHandCount - currentHandCount;
                        for (int i = 0; i < drawCount; i++)
                        {
                            RectTransform drawnTile = uiManager.EnemyWallUI.GrabEnemyTile();
                            if (drawnTile != null)
                            {
                                int newTileId = board.CurrentEnemyHandTiles[currentHandCount + i];
                                InitializeTileComponent(drawnTile, -1, false);
                                uiManager.EnemyHandUI.AddEnemyTile(drawnTile, -1, newTileId);
                            }
                        }
                    }
                }
            }

            // 毎回の更新で、透視状態だけはフルリビルドに関わらず必ず同期する
            SyncLocalExposedState(board);

            if (uiManager.WaitUI != null && (uiManager.CurrentPhaseStatus == RoundStatus.Discard || uiManager.CurrentPhaseStatus == RoundStatus.HandSelection))
            {
                if (board.CurrentWaitTiles != null && board.CurrentWaitTiles.Count > 0)
                {
                    uiManager.WaitUI.gameObject.SetActive(true);
                    uiManager.WaitUI.DisplayWaits(board.CurrentWaitTiles);
                }
            }
        }

        public void InitializeTileComponent(RectTransform rt, int id, bool inHand)
        {
            var visual = rt.GetComponent<TileVisual>();
            if (visual != null)
            {
                visual.SetHoverHighlight(false);
                visual.SetFuritenHighlight(false);
                visual.SetExposed(false);
                
                if (uiManager.TileResourceManager != null)
                {
                    visual.SetTile(id, uiManager.TileResourceManager.GetTileSprite(id));
                }
            }

            var interaction = rt.GetComponent<TileInteraction>();
            if (interaction == null) interaction = rt.gameObject.AddComponent<TileInteraction>();
            
            Canvas canvas = GetComponentInParent<Canvas>();
            if (canvas == null) canvas = FindFirstObjectByType<Canvas>();
            
            interaction.Initialize(id, inHand, uiManager, canvas);
        }

        private void SyncLocalExposedState(Managers.BoardStateManager board)
        {
            List<int> localExposedActualIds = new List<int>();
            foreach (int exposedIdx in board.ExposedLocalHandWallIndexes)
            {
                if (exposedIdx >= 0 && exposedIdx < board.OriginalWallTiles.Count)
                {
                    localExposedActualIds.Add(board.OriginalWallTiles[exposedIdx]);
                }
            }

            if (uiManager.HandUI != null)
            {
                foreach (var rt in uiManager.HandUI.GetHandSlots())
                {
                    if (rt == null) continue;
                    var interaction = rt.GetComponent<TileInteraction>();
                    var visual = rt.GetComponent<TileVisual>();
                    if (interaction != null && visual != null)
                    {
                        bool isExposed = localExposedActualIds.Contains(interaction.TileId);
                        if (isExposed) localExposedActualIds.Remove(interaction.TileId);
                        visual.SetExposed(isExposed);
                    }
                }
            }

            if (uiManager.WallUI != null)
            {
                foreach (var rt in uiManager.WallUI.GetWallSlots())
                {
                    if (rt == null) continue;
                    var interaction = rt.GetComponent<TileInteraction>();
                    var visual = rt.GetComponent<TileVisual>();
                    if (interaction != null && visual != null)
                    {
                        bool isExposed = localExposedActualIds.Contains(interaction.TileId);
                        if (isExposed) localExposedActualIds.Remove(interaction.TileId);
                        visual.SetExposed(isExposed);
                    }
                }
            }
        }

        private void UpdateSelectedTileVisuals()
        {
            var selectedIds = BoardStateManager.Instance.SelectedTileIds;
            if (uiManager.WallUI != null)
            {
                foreach (var t in uiManager.WallUI.GetWallSlots())
                {
                    var interaction = t.GetComponent<TileInteraction>();
                    if (interaction != null)
                    {
                        t.localPosition = interaction.OriginalWallPosition;
                    }
                }
            }
        }

        private Vector2 GetScreenPosition(RectTransform rt)
        {
            Canvas canvas = rt.GetComponentInParent<Canvas>();
            Camera cam = null;
            if (canvas != null && canvas.renderMode != RenderMode.ScreenSpaceOverlay)
            {
                cam = canvas.worldCamera;
                if (cam == null) cam = Camera.main;
            }
            return RectTransformUtility.WorldToScreenPoint(cam, rt.position);
        }

        private void HandleTileMovedToHand(int tileId)
        {
            if (uiManager.IsTransitioning) return;

            if (uiManager.WallUI != null && uiManager.HandUI != null)
            {
                RectTransform movedTile = uiManager.WallUI.GrabTile(tileId);
                if (movedTile != null)
                {
                    Vector2 startScreenPos = GetScreenPosition(movedTile);
                    uiManager.HandUI.AddTileToHand(movedTile, tileId);
                    
                    Camera cam = null;
                    Canvas canvas = uiManager.HandUI.GetComponentInParent<Canvas>();
                    if (canvas != null && canvas.renderMode != RenderMode.ScreenSpaceOverlay)
                    {
                        cam = canvas.worldCamera;
                        if (cam == null) cam = Camera.main;
                    }

                    Vector2 localPoint;
                    RectTransform container = movedTile.parent as RectTransform;
                    if (container != null && RectTransformUtility.ScreenPointToLocalPointInRectangle(container, startScreenPos, cam, out localPoint))
                    {
                        movedTile.anchoredPosition = localPoint;
                    }
                    else
                    {
                        movedTile.anchoredPosition = Vector2.zero;
                    }
                }
            }
        }

        private void HandleTileMovedToWall(int tileId)
        {
            if (uiManager.IsTransitioning) return;

            if (uiManager.HandUI == null || uiManager.WallUI == null) return;

            RectTransform movedTile = null;
            foreach (RectTransform t in uiManager.HandUI.GetHandSlots())
            {
                var interaction = t.GetComponent<TileInteraction>();
                if (interaction != null && interaction.TileId == tileId)
                {
                    movedTile = t;
                    break;
                }
            }

            if (movedTile != null)
            {
                Vector2 startScreenPos = GetScreenPosition(movedTile);
                uiManager.HandUI.RemoveTileFromHand(movedTile, tileId);
                uiManager.WallUI.ReturnTileToWall(movedTile, tileId);
                
                Camera cam = null;
                Canvas canvas = uiManager.WallUI.GetComponentInParent<Canvas>();
                if (canvas != null && canvas.renderMode != RenderMode.ScreenSpaceOverlay)
                {
                    cam = canvas.worldCamera;
                    if (cam == null) cam = Camera.main;
                }

                Vector2 localPoint;
                RectTransform container = movedTile.parent as RectTransform;
                if (container != null && RectTransformUtility.ScreenPointToLocalPointInRectangle(container, startScreenPos, cam, out localPoint))
                {
                    movedTile.anchoredPosition = localPoint;
                }
                else
                {
                    movedTile.anchoredPosition = Vector2.zero;
                }
            }
        }

        public System.Collections.IEnumerator PlayPerspectiveAnimation(List<int> newlyExposed)
        {
            if (uiManager.EnemyWallUI == null) yield break;

            RebuildAllTilesFromState(newlyExposed);

            yield return new WaitForSeconds(0.5f);

            List<UnityEngine.UI.Image> glowingImages = new List<UnityEngine.UI.Image>();

            foreach (int index in newlyExposed)
            {
                if (index >= 0 && index < uiManager.EnemyWallUI.GetEnemyWallSlots().Count)
                {
                    Transform slot = uiManager.EnemyWallUI.GetEnemyWallSlots()[index];
                    if (slot != null && slot.childCount > 0)
                    {
                        RectTransform rt = slot.GetChild(0) as RectTransform;
                        if (rt != null)
                        {
                            int actualTileId = Managers.BoardStateManager.Instance.OriginalEnemyWallTiles[index];
                            InitializeTileComponent(rt, actualTileId, true);

                            UnityEngine.UI.Image img = rt.GetComponent<UnityEngine.UI.Image>();
                            if (img != null) glowingImages.Add(img);

                            Vector3 origScale = rt.localScale;
                            float duration = 0.25f;
                            for (float t = 0; t < duration; t += Time.deltaTime)
                            {
                                float s = Mathf.Lerp(1f, 1.3f, Mathf.PingPong(t * (1f / (duration / 2f)), 1f));
                                rt.localScale = origScale * s;
                                yield return null;
                            }
                            rt.localScale = origScale;
                        }
                    }
                }
            }

            // カットイン演出(2.0s) + HP減少(1.0s) = 計3.0s 待つ
            float waitedSoFar = 0.5f + (0.25f * newlyExposed.Count);
            float timeToWait = 3.0f - waitedSoFar;
            if (timeToWait > 0)
            {
                yield return new WaitForSeconds(timeToWait);
            }

            // 演出終了後、2秒間めくられた牌を光らせてアピール
            float glowDuration = 2.0f;
            Color originalColor = Color.white;
            Color glowColor = new Color(1.0f, 0.8f, 0.2f); // 黄色っぽく発光
            
            for (float t = 0; t < glowDuration; t += Time.deltaTime)
            {
                float pingPong = Mathf.PingPong(t * 3f, 1f); 
                Color currentColor = Color.Lerp(originalColor, glowColor, pingPong);
                foreach (var img in glowingImages)
                {
                    if (img != null) img.color = currentColor;
                }
                yield return null;
            }

            // 元の色に戻す
            foreach (var img in glowingImages)
            {
                if (img != null) img.color = originalColor;
            }

            if (uiManager.PhaseController != null)
            {
                uiManager.PhaseController.HandlePhaseVisibility(uiManager.CurrentPhaseStatus);
            }
        }

        private bool UpdateTileIdInUI(int oldId, int newId)
        {
            bool found = false;
            if (uiManager.WallUI != null)
            {
                foreach (var slot in uiManager.WallUI.GetWallSlots())
                {
                    if (slot == null) continue;
                    var interaction = slot.GetComponent<TileInteraction>();
                    if (interaction != null && interaction.TileId == oldId)
                    {
                        interaction.TileId = newId;
                        var visual = slot.GetComponent<TileVisual>();
                        if (visual != null && uiManager.TileResourceManager != null)
                        {
                            visual.SetTile(newId, uiManager.TileResourceManager.GetTileSprite(newId), uiManager.TileResourceManager);
                        }
                        found = true;
                        break;
                    }
                }
            }
            if (!found && uiManager.HandUI != null)
            {
                foreach (var slot in uiManager.HandUI.GetHandSlots())
                {
                    if (slot == null) continue;
                    var interaction = slot.GetComponent<TileInteraction>();
                    if (interaction != null && interaction.TileId == oldId)
                    {
                        interaction.TileId = newId;
                        var visual = slot.GetComponent<TileVisual>();
                        if (visual != null && uiManager.TileResourceManager != null)
                        {
                            visual.SetTile(newId, uiManager.TileResourceManager.GetTileSprite(newId), uiManager.TileResourceManager);
                        }
                        found = true;
                        break;
                    }
                }
            }
            return found;
        }

        public IEnumerator PlayHandSortAnimationRoutine()
        {
            if (uiManager.HandUI == null) yield break;

            var handSlots = uiManager.HandUI.GetHandSlots();
            if (handSlots == null || handSlots.Count == 0) yield break;

            var board = BoardStateManager.Instance;
            var currentHandIds = board.CurrentHandTiles;

            Dictionary<RectTransform, Vector2> startPositions = new Dictionary<RectTransform, Vector2>();
            foreach (var slot in handSlots)
            {
                startPositions[slot] = slot.anchoredPosition;
            }

            List<RectTransform> sortedSlots = new List<RectTransform>();
            List<RectTransform> unsortedSlots = new List<RectTransform>(handSlots);
            
            foreach (int targetId in currentHandIds)
            {
                RectTransform foundSlot = null;
                foreach(var slot in unsortedSlots)
                {
                    var visual = slot.GetComponent<TileVisual>();
                    if (visual != null && visual.GetId() == targetId)
                    {
                        foundSlot = slot;
                        break;
                    }
                }
                if (foundSlot != null)
                {
                    sortedSlots.Add(foundSlot);
                    unsortedSlots.Remove(foundSlot);
                }
                else if (unsortedSlots.Count > 0)
                {
                    sortedSlots.Add(unsortedSlots[0]);
                    unsortedSlots.RemoveAt(0);
                }
            }

            for (int i = 0; i < sortedSlots.Count; i++)
            {
                sortedSlots[i].SetSiblingIndex(i);
            }

            UnityEngine.UI.LayoutRebuilder.ForceRebuildLayoutImmediate(uiManager.HandUI.GetComponent<RectTransform>());
            yield return null;

            Dictionary<RectTransform, Vector2> targetPositions = new Dictionary<RectTransform, Vector2>();
            foreach (var slot in sortedSlots)
            {
                targetPositions[slot] = slot.anchoredPosition;
            }

            var layoutGroup = uiManager.HandUI.GetComponentInChildren<UnityEngine.UI.LayoutGroup>();
            bool wasLayoutEnabled = false;
            if (layoutGroup != null)
            {
                wasLayoutEnabled = layoutGroup.enabled;
                layoutGroup.enabled = false;
            }

            foreach (var slot in sortedSlots)
            {
                slot.anchoredPosition = startPositions[slot];
            }

            float duration = 0.4f;
            float elapsed = 0f;

            while (elapsed < duration)
            {
                elapsed += Time.deltaTime;
                float t = Mathf.Clamp01(elapsed / duration);
                t = 1f - Mathf.Pow(1f - t, 3f);

                foreach (var slot in sortedSlots)
                {
                    slot.anchoredPosition = Vector2.Lerp(startPositions[slot], targetPositions[slot], t);
                }
                yield return null;
            }

            foreach (var slot in sortedSlots)
            {
                slot.anchoredPosition = targetPositions[slot];
            }

            if (layoutGroup != null)
            {
                layoutGroup.enabled = wasLayoutEnabled;
            }

            uiManager.HandUI.GetHandSlots().Clear();
            uiManager.HandUI.GetHandSlots().AddRange(sortedSlots);

            RebuildAllTilesFromState(null);
        }

        public IEnumerator PlayTransitionAnimationRoutine(System.Action onUpdateState)
        {
            if (uiManager.WallUI == null && uiManager.HandUI == null)
            {
                onUpdateState?.Invoke();
                yield break;
            }

            uiManager.SetIsTransitioning(true);

            // 1. 状態更新前の配置を記録
            List<int> oldHand = new List<int>(BoardStateManager.Instance.CurrentHandTiles);
            List<int> oldWall = new List<int>(BoardStateManager.Instance.CurrentWallTiles);

            // 2. 状態を更新（IsTransitioning=true なので RebuildAllTilesFromState はスキップされる）
            onUpdateState?.Invoke();

            List<int> newHand = new List<int>(BoardStateManager.Instance.CurrentHandTiles);
            List<int> newWall = new List<int>(BoardStateManager.Instance.CurrentWallTiles);

            List<int> movedToHand = new List<int>();
            List<int> oldHandTemp = new List<int>(oldHand);
            foreach (int id in newHand) 
            {
                if (oldHandTemp.Contains(id)) oldHandTemp.Remove(id);
                else movedToHand.Add(id);
            }

            List<int> movedToWall = new List<int>();
            List<int> oldWallTemp = new List<int>(oldWall);
            foreach (int id in newWall) 
            {
                if (oldWallTemp.Contains(id)) oldWallTemp.Remove(id);
                else movedToWall.Add(id);
            }

            // 3. 手牌から山牌へ戻る牌を視覚的に移動
            foreach (int id in movedToWall)
            {
                if (uiManager.WallUI != null && uiManager.HandUI != null)
                {
                    RectTransform tileRt = null;
                    foreach(var slot in uiManager.HandUI.GetHandSlots()) {
                        var inter = slot.GetComponent<TileInteraction>();
                        if (inter != null && inter.TileId == id) { tileRt = slot; break; }
                    }
                    if (tileRt != null) {
                        Vector2 startScreenPos = GetScreenPosition(tileRt);
                        
                        uiManager.HandUI.RemoveTileFromHand(tileRt, id);
                        uiManager.WallUI.ReturnTileToWall(tileRt, id);
                        
                        // アニメーションのため、親が変わった直後の位置を元に戻す
                        Camera cam = null;
                        Canvas canvas = uiManager.WallUI.GetComponentInParent<Canvas>();
                        if (canvas != null && canvas.renderMode != RenderMode.ScreenSpaceOverlay)
                        {
                            cam = canvas.worldCamera;
                            if (cam == null) cam = Camera.main;
                        }

                        Vector2 localPoint;
                        RectTransform container = tileRt.parent as RectTransform;
                        if (container != null && RectTransformUtility.ScreenPointToLocalPointInRectangle(container, startScreenPos, cam, out localPoint))
                        {
                            tileRt.anchoredPosition = localPoint;
                        }
                    }
                }
            }

            // 4. 山牌から手牌へ移動する牌を視覚的に移動
            foreach (int id in movedToHand)
            {
                if (uiManager.WallUI != null && uiManager.HandUI != null)
                {
                    RectTransform tileRt = uiManager.WallUI.GrabTileById(id);
                    if (tileRt != null)
                    {
                        Vector2 startScreenPos = GetScreenPosition(tileRt);
                        
                        uiManager.HandUI.AddTileToHand(tileRt, id);
                        
                        // アニメーションのため、親が変わった直後の位置を元に戻す
                        Camera cam = null;
                        Canvas canvas = uiManager.HandUI.GetComponentInParent<Canvas>();
                        if (canvas != null && canvas.renderMode != RenderMode.ScreenSpaceOverlay)
                        {
                            cam = canvas.worldCamera;
                            if (cam == null) cam = Camera.main;
                        }
                        Vector2 localPoint;
                        RectTransform container = tileRt.parent as RectTransform;
                        if (container != null && RectTransformUtility.ScreenPointToLocalPointInRectangle(container, startScreenPos, cam, out localPoint))
                        {
                            tileRt.anchoredPosition = localPoint;
                        }
                    }
                }
            }

            // 5. 新しい配置で手牌のレイアウトのみ更新（WallUIの再整列は行わず、元の位置のまま穴を開けたり埋めたりする）
            if (uiManager.HandUI != null)
            {
                uiManager.HandUI.UpdateLayout(uiManager.CurrentPhaseStatus);
            }

            // 6. ユーザー指定のアニメーション時間 (0.2秒) 待機
            float duration = 0.2f;
            yield return new WaitForSeconds(duration);

            uiManager.SetIsTransitioning(false);
            
            // 7. Rebuild時にプール回収が走らないよう、内部の同期用キャッシュを最新化
            _lastWallIds = new List<int>(BoardStateManager.Instance.CurrentWallTiles);
            _lastHandIds = new List<int>(BoardStateManager.Instance.CurrentHandTiles);
        }
    }
}
